export const SET_LOAD_STATUS = "MAIN/SET_LOAD_STATUS";
export const SET_USER_STATUS = "MAIN/SET_USER_STATUS";
export const SET_QUESTION_PACK = "MAIN/SET_QUESTION_PACK";
export const UPDATE_ITEM = "MAIN/UPDATE_ITEM";
